### ISSUE TITLE
Error with network.compress()

### ISSUE THREAD

**Issue by arichelle** [SystemsBioinformatics/ecmtool#12]
Hi,

I keep running into the same error when using network.compress()

Traceback is as follows:
>compress
>compress_inner
>cancel_clementine
> clementine_equality_compression
>redund
    with open(matrix_nonredundant_path) as file:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\...\\ecmtool\\ecmtool\\tmp\\matrix_nored0.ine'

Any suggestions?

Thank in advance

**Comment by dhdegroot** [comment]
Hi,

@tjclement can probably help you with this. For now, I know that we have had some problems already with the tmp-folder not being created, but I thought we had solved it before. @arichelle could you check for us if the tmp-folder exists at the reported path?

Best,
Daan

**Comment by arichelle** [comment]
Yes it exits but the only .ine file in it is named "matrix0"

**Comment by tjclement** [comment]
Hi @arichelle, it seems that the tool we use to removed redundant vectors (called _redund_) is not writing its nonredundant output file given your input matrix. Could you share your _matrix0.ine_ file with us here, so we can have a look into why redund trips on it?

**Comment by arichelle** [comment]
Here it goes
[matrix0.zip](https://github.com/SystemsBioinformatics/ecmtool/files/6607732/matrix0.zip)

**Comment by tjclement** [comment]
This is peculiar: I'm not able to reproduce what you're seeing. On Windows, like you're using, running `redund` on the file you sent seems to result in a reduced matrix just fine.

Can you share more about your environment, like which version of Windows and version of Python are you using, and whether you pip installed or git cloned ecmtool? It would also be very helpful if you could share the network that you're trying to compress.

Thanks!

**Comment by arichelle** [comment]
Hello,
I git cloned the repo, I'm using Spyder as Python environment with Python 3.8. and I've Windows 10 Enterprise.
Here the script I try to run 

[ExampleUseECM.zip](https://github.com/SystemsBioinformatics/ecmtool/files/6637251/ExampleUseECM.zip)

**Comment by tjclement** [comment]
Hey @arichelle, with Spyder installed on a Windows 10 machine the attached code does not throw the error you're seeing. I did the following:

- Git cloned ecmtool
- Copied your example script in the top-level directory of the cloned ecmtool repository
- Installed Spyder, and set it to use the (3.7) python installation on this system
- pip installed ecmtool/requirements.txt
- pip installed sympy==1.7.1 (related to the bug in cbmpy mentioned in your other opened issue)
- Ran your script

There was a different issue in the script, where making a list of external metabolites went wrong after calculating the ECMs. @dhdegroot fixed that in the script that yours was based on yesterday: https://github.com/SystemsBioinformatics/ecmtool/commit/d5c51920cf792187606a12ce41f12c2e58d4d058.

Regarding the issue you're seeing with removal of redundant vectors, I am not sure how we can best help as we're not able to reproduce it so far. Perhaps it's got something to do with your Python (or anaconda) environment?

**Comment by arichelle** [comment]
yes it was most likely a problem with my python environment. I was able to run without trouble the example on a VM of Azure.
