### ISSUE TITLE
sympy version check in cbmpy pckg

### ISSUE THREAD

**Issue by arichelle** [SystemsBioinformatics/ecmtool#13]
Hi,

(me again) another little issue I ran into is the version check of sympy used in the cbmpy package.

In mutliple files, the version check is done by using
> if int(sympy.__version__.split('.')[1]) >= 7 and int(sympy.__version__.split('.')[2]) >= 4:

As the last version of sympy is 1.8, this leads to an indexing problem
I fixed it by simply removing the second part of the statement but if you want to ensure version below are 1.7.4 are bot used you will need to introduce.

Maybe I should directly contact O. Brett on this topic but rather let you know that this prevent the run of test codes and examples

best

**Comment by dhdegroot** [comment]
Hi,

Ah, that's a good point. Indeed, this is something that Brett can help you with best. We can see if he responds if I tag him: @bgoli, and otherwise, please contact him directly via the cbmpy-github. That will probably be the most direct way.

Best,

**Comment by tjclement** [comment]
Hi @arichelle, whilst trying to reproduce your other reported issue on a new Windows machine I ran into the same issue you mentioned here regarding cbmpy. It appears that this issue has been reported on the cbmpy repository already: https://github.com/SystemsBioinformatics/cbmpy/issues/33

A workaround you could consider for now is to install sympy at version 1.7.1 (the latest 1.7.x released on pypi). As there are many files in cbmpy that check the version of sympy, installing this specific version might be the easiest way to avoid issues in cbmpy.
