### ISSUE TITLE
GLPK is not recognized

### ISSUE THREAD

**Issue by ylwed** [SystemsBioinformatics/ecmtool#14]
Hello!

I'm trying to install ecmtool on a HPC environment on my campus in a singularity container. So far, I'm having a problem with the GLPK solver: Even though GLPK is installed and loaded in the environment, the program states that it is not available. I'm not sure whether the problem is the installation or loading of the GLPK solver or if it is a problem with ecmtool. It does seem ecmtool is able to use CPLEX, but only the python interface is installed in the environment, so it is likely not actually used. 

If anyone would like to look into this, I would be happy to send the singularity definition file, the SLURM script and the log-files.

**Comment by dhdegroot** [comment]
Hi,
@EBaalhuis agreed to look into this. He will contact you shortly.

**Comment by EBaalhuis** [comment]
Hi @ylwed can you send me the singularity definition file, the SLURM script and the log-files?

**Comment by ylwed** [comment]
Hello, Tom!

Thank you so much for the talk yesterday! I have attached the singularity definition file in this mail, so you are free to look into it!

Regards,
Ylva

Fra: Tom ***@***.***>
Sendt: fredag 8. april 2022 kl. 17.21
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [SystemsBioinformatics/ecmtool] GLPK is not recognized (Issue #14)


Update on this: Ylva has ecmtool running in singularity, but there appears to be a crash during the compression phase. She'll send over the singularity config to me, and I'll then test it locally to see what might be going on.
