### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by hites77** [SystemsBioinformatics/ecmtool#15]
In the published paper there is clustering R script which has mentioned - metab_info_ecolicore.csv and  metab_info_bacteroid.csv file inside data directory but is not here.

**Comment by dhdegroot** [comment]
Dear @hites77,
You are absolutely right. This information was missing here. It went wrong because I was working on the clustering in a separate Github-repo. Can you check if https://github.com/dhdegroot/cluster_ECMs contains everything you need?

**Comment by hites77** [comment]
Thanks, got the file
