### ISSUE TITLE
ECM results missing key metabolism or biomass synthesis

### ISSUE THREAD

**Issue by maxEntropyProd** [SystemsBioinformatics/ecmtool#16]
Hi,

I've been running ecmtool on a few GEMs from BiGG (as well as a couple others), but I'm getting results that appear incomplete and I've yet to figure out why. Here is an example of using the latest version of ecmtool on a methanogen:

Methanosarcina barkeri str. Fusaro GEM iAF692 http://bigg.ucsd.edu/models/iAF692
This is a methanotroph, yet there is no ECM where hydrogen is consumed, only produced, but one of the primary catabolic pathway is
4 H2 + CO2 -> CH4 + 2 H2O
which is not found in the list of ECMs

I have another GEM where flux analysis show biomass synthesis; however, no ECMs are found that involve biomass synthesis. Unfortunately, I can't point to that GEM. I also didn't get any biomass ECM for a Synechocystis GEM (http://bigg.ucsd.edu/models/iJN678) when I ran an earlier version of ecmtool; however, when I run the latest version of ecmtool on that GEM now it finds a problem with one of the reactions (R_EX_photon_e) that has both lower and upper bounds of 0. I can remove that reaction, but that make it harder for you to verify.

I realize this is not much info to go on, but do you see a reason why there are no hydrogen consuming ECMs for the iAF692 GEM above?

Thanks!
-joe

**Comment by maxEntropyProd** [comment]
OK, never mind. I see there is a lower bound constraint on the H2 exchange reaction for iAF692 GEM. Perhaps other GEMs I have looked at also contain poor choices on exchange reactions and explains why they don't produce what I would consider basic/obvious ECMs.

**Comment by dhdegroot** [comment]
Hi Joe,
Yes, when running ecmtool it is really important to check the preprocessing. You can make the metabolites and reactions be printed with the arguments "--print_metabolites True" and "--print_reactions True". In the output, you can then see whether the organism is actually able to take up and secrete the correct metabolites. We have tried to infer these input- and output-metabolites as generally as possible, but different model-standards use different conventions, which makes it quite hard. So, please always check this.

Personally, as a sanity check, I like running an FBA that produces biomass, and then check which metabolites are taken up and produced. I then use that information to set the input-, and output-metabolites in ecmtool. Then I am certain that there must be an ECM that produces biomass.

**Comment by maxEntropyProd** [comment]
Thanks for the tip Daan! I have run FBA on the GEMs that don't produce a biomass synthesis ECM, and they do show biomass being produce in the FBA; however, I suspect there is something in the GEMs that are causing the issue. I will continue to sift through them. Thanks for your help!
