### ISSUE TITLE
Solution differences between Windows vs linux (centOS 7)

### ISSUE THREAD

**Issue by maxEntropyProd** [SystemsBioinformatics/ecmtool#18]
When I used a slightly modified GEM from here: https://onlinelibrary.wiley.com/doi/10.1002/biot.201200266 for iMG746, I get significantly different solutions when I run ecmtool on Windows vs CintOS 7. For instance, the Windows solution produces 3084 ECMs, while linux produces 57724 ECMs. The windows solution does not include any ECMs with the objective function (which I didn't understand why), but the linux solution produces many of those.  I'm using the recent version of ecmtool on both boxes. The GEM can be grabbed here: http://eco37.mbl.edu/GEMs/iMG746_ExchangeFix.xml if you would like to test. 

cheers,
-joe

**Comment by dhdegroot** [comment]
Hi Joe,
Thank you for mentioning this, and in general for your help in improving ecmtool. @tjclement is going to look into this issue, and we will let you know once we know what's going wrong.

**Comment by maxEntropyProd** [comment]
Glad to help, but there is a non trivial probability it's me going wrong. If so, sorry for wasting your time.

**Comment by tjclement** [comment]
Hi @maxEntropyProd, sorry for letting this linger for a while; it's an incredibly busy time.. I'm hoping to be able to look into this soon. Keep you posted!

**Comment by maxEntropyProd** [comment]
Hi Tom, no problem. I'm continuing to run various GEMs, but I've only had one or two successes due to a variety of reasons. Some are GEM related (old SMBL version, but easy to correct), upper and lower bound equalities (easy to fix), SMBL format not correct (less obvious), ecmtool crashes (often in ploco, not clear why), ECMs violate mass conservation (probably a GEM issue), run exceeds memory (nodes only have  96 GB), or their still running (currently have jobs running after 8, 14 and 17 days).

I plan on working on this approach for a while and have some funds to do so; consequently, if there is anything I can do to help, just ask!
cheers,
-joe

**Comment by dhdegroot** [comment]
Dear Joe,

Please excuse us for not getting back to you for a while. Thanks for working on this approach, your user experience is very welcome. I will send you an email about possibilities to help.

Best,
Daan

**Comment by dhdegroot** [comment]
Hi Joe,

This email was from a long time ago, but Tom and I plan to sit together for a few days in March to fix some issues in ecmtool. Most importantly, we want to introduce standardized tests on some datasets so that for all edits/updates of ecmtool it can be easily tested whether it is still correct. Other than that, we also want to look at some small functions that turn out to be computational bottlenecks when ecmtool is run on large networks. 

I was wondering if you had additional inputs/issues that you would like us to look at. Tom and I are not often finding the time to sit together and improve ecmtool, so I would like to do as much as possible in these couple of days.

Best,
Daan

**Comment by maxEntropyProd** [comment]
Hi Daan,

Thanks for the heads up! I'm currently installing a large addition to my cluster,  but once that's up, I'm planning on testing out emctool2.0, which looks quite interesting! Most of my concerns were associated with using emctool with full bacterial GEMs, for which most just ran for weeks or months. I finally shut them down once I started the cluster upgrade. I have some other jobs I currently need to finish, but condensing GEMs into ECMs is still a research area I'm quite interested in. I'll reach out once I start running ecmtool2.0, but it might be a month or two until I can get back to that.

cheers,
-joe
